# Generated by Django 3.1.1 on 2020-09-22 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_desc', models.TextField(blank=True)),
                ('task_taker', models.CharField(blank=True, max_length=255)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_taken', models.DateTimeField(blank=True, null=True)),
                ('time_done', models.DateTimeField(blank=True, null=True)),
                ('task_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
